syntax = "proto3";

message PlanCostShares {
  string objectId = 1;
  string objectType = 2;
  int32 deductible = 3;
  int32 copay = 4;
  string _org = 5;
}

message LinkedService {
  string objectId = 1;
  string objectType = 2;
  string name = 3;
  string _org = 4;
}

message PlanServiceCostShares {
  string objectId = 1;
  string objectType = 2;
  int32 deductible = 3;
  int32 copay = 4;
  string _org = 5;
}

message LinkedPlanService {
  string objectId = 1;
  string objectType = 2;
  LinkedService linkedService = 3;
  PlanServiceCostShares planserviceCostShares = 4;
  string _org = 5;
}

message Plan {
  string objectId = 1;
  string objectType = 2;
  string planType = 3;
  string creationDate = 4;
  PlanCostShares planCostShares = 5;
  repeated LinkedPlanService linkedPlanServices = 6;
  string _org = 7;
}
